#FROM nvcr.io/nvidia/tensorrt:22.05-py3
FROM ubuntu

SHELL ["/bin/bash", "-c"]

# Setup user account
# id -g, id -u
ARG uid=1014
ARG gid=1014
RUN groupadd -r -f -g ${gid} tglee && useradd -o -r -l -u ${uid} -g ${gid} -ms /bin/bash tglee
RUN usermod -aG sudo tglee
RUN echo 'tglee:tglee1' | chpasswd
RUN mkdir -p /django-react-project && chown tglee /django-react-project

WORKDIR /django-react-project


# Required to build Ubuntu 20.04 without user prompts with DLFW container
ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL ko_KR.UTF-8
# install
RUN apt-get update && apt-get install -y sudo && \
    apt-get install -y libgl1-mesa-glx git locales && \
    locale-gen ko_KR.UTF-8
# RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

# container에 git 설치 & 프로젝트 필요 소스 다운로드
RUN apt-get -qq install curl --yes
RUN apt-get install git -y
RUN mkdir -p /django-react-project/react && chown tglee /django-react-project/react
RUN git clone https://github.com/tak-hirosi-reactproject-search/react_search_project.git /django-react-project/react
RUN mkdir -p /django-react-project/django && chown tglee /django-react-project/django
RUN git clone https://github.com/tak-hirosi-reactproject-search/video_search.git /django-react-project/django


# react 설치
FROM node:latest
#RUN curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
#RUN sudo apt-get -qq install nodejs --yes

WORKDIR /django-react-project/react
RUN npm install

EXPOSE 3000

# django 설치
FROM python:latest
WORKDIR /django-react-project/django
RUN pip install -r requirements.txt

EXPOSE 8000

WORKDIR /django-react-project



USER tglee
RUN ["/bin/bash"]