# Generated by Django 4.1.1 on 2022-09-25 22:58

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labels_mainclass_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Mainclass')),
            ],
        ),
        migrations.CreateModel(
            name='video_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_path', models.FilePathField(max_length=200, null=True, path=pathlib.PurePosixPath('/workspace/test_jhlee/search_module'), verbose_name='SOURCE PATH')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('fps', models.PositiveSmallIntegerField(null=True, verbose_name='FPS')),
                ('last_frame', models.PositiveSmallIntegerField(null=True, verbose_name='Last Frame')),
            ],
        ),
        migrations.CreateModel(
            name='labels_attributes_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('mainclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.labels_mainclass_type', verbose_name='Mainclass')),
            ],
        ),
        migrations.CreateModel(
            name='labels_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('value', models.CharField(max_length=30, verbose_name='Attributes')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.labels_attributes_type', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='bbox_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_num', models.PositiveBigIntegerField(verbose_name='Frame')),
                ('obj_id', models.PositiveSmallIntegerField(verbose_name='Object ID')),
                ('crop_img_path', models.FilePathField(max_length=200, path=pathlib.PurePosixPath('/workspace/test_jhlee/search_module'))),
                ('mainclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.labels_mainclass_type', verbose_name='Mainclass')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.video_data', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='bbox_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.labels_attributes', verbose_name='Attributes')),
                ('bbox_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.bbox_data', verbose_name='BBOX ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='labels_attributes_type',
            constraint=models.UniqueConstraint(fields=('mainclass', 'type'), name='unique frame'),
        ),
        migrations.AddConstraint(
            model_name='labels_attributes',
            constraint=models.UniqueConstraint(fields=('type', 'index'), name='unique attribute'),
        ),
        migrations.AddConstraint(
            model_name='bbox_data',
            constraint=models.UniqueConstraint(fields=('video', 'frame_num', 'obj_id'), name='unique object'),
        ),
        migrations.AddConstraint(
            model_name='bbox_attributes',
            constraint=models.UniqueConstraint(fields=('bbox_id', 'attributes'), name='unique box attributes'),
        ),
    ]
