# Generated by Django 4.1.1 on 2022-09-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbox_attributes',
            old_name='bbox_id',
            new_name='bbox',
        ),
        migrations.AlterField(
            model_name='video_data',
            name='fps',
            field=models.FloatField(null=True, verbose_name='FPS'),
        ),
        migrations.AlterField(
            model_name='video_data',
            name='last_frame',
            field=models.FloatField(null=True, verbose_name='Last Frame'),
        ),
    ]
