# Generated by Django 4.0.8 on 2022-10-24 00:13

import django.core.validators
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_alter_video_data_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaded_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
            ],
        ),
        migrations.RemoveField(
            model_name='video_data',
            name='video',
        ),
        migrations.AddField(
            model_name='video_data',
            name='name',
            field=models.CharField(default='temp', max_length=100, verbose_name='NAME'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_data',
            name='src_path',
            field=models.FilePathField(max_length=200, null=True, path=pathlib.PurePosixPath('/workspace/test_jhlee/video_search'), verbose_name='SOURCE PATH'),
        ),
        migrations.AlterModelTable(
            name='search_result',
            table=None,
        ),
    ]
